- name: Get sha256sum.txt for serverless
  ansible.builtin.uri:
    url: "{{ serverless_url }}/{{ serverless_version }}/{{ hash_file }}"
    return_content: yes
  register: serverless_hash_file

- name: Split up the downloaded sha256sum file
  ansible.builtin.set_fact:
    serverless_hashes: "{{ serverless_hash_file.content.split() }}"

- name: Match hash for Mac serverless (kn) binary
  ansible.builtin.set_fact:
    serverless_mac_hash: "{{ serverless_hashes[index - 1] }}"
  when: serverless_mac_binary == serverless_hashes[index]
  loop: "{{ serverless_hashes }}"
  loop_control:
    index_var: index

- name: Match hash for Linux serverless (kn) binary
  ansible.builtin.set_fact:
    serverless_linux_hash: "{{ serverless_hashes[index - 1] }}"
  when: serverless_linux_binary == serverless_hashes[index | int]
  loop: "{{ serverless_hashes }}"
  loop_control:
    index_var: index

- name: Creating openshift-serverless.rb Forumla from template
  ansible.builtin.template:
    src: "templates/openshift-serverless.j2"
    dest: "{{ formula_directory }}/openshift-serverless.rb"
    mode: "0644"
