- name: Figuring out the latest odo version - step 1 - getting list
  ansible.builtin.uri:
    url: "{{ serverless_url }}?F=0"
    return_content: yes
  retries: 3
  delay: 3
  register: serverless_dir_list

- name: Getting version - step 2 - parsing html
  ansible.builtin.set_fact:
    serverless_temp_1: "{{ serverless_dir_list.content.split() }}"

- name: Getting version - step 3 - parsing html (again)
  ansible.builtin.set_fact:
    serverless_temp_2: "{{ item.split('/') }}"
  loop: "{{ serverless_temp_1 }}"
  when: item is regex("^[0-9]*\\.[0-9]*\\.[0-9]*")

- name: Getting version - step 4 - setting the version
  ansible.builtin.set_fact:
    serverless_version: "{{ serverless_temp_2.0 }}"

- name: Get sha256sum.txt for serverless
  ansible.builtin.uri:
    url: "{{ serverless_url }}/{{ serverless_version }}/{{ hash_file }}"
    return_content: yes
  retries: 3
  delay: 3
  register: serverless_hash_file

- name: Split up the downloaded sha256sum file
  ansible.builtin.set_fact:
    serverless_hashes: "{{ serverless_hash_file.content.split() }}"

- name: Match hash for Mac serverless (kn) binary
  ansible.builtin.set_fact:
    serverless_mac_hash: "{{ serverless_hashes[index - 1] }}"
  when: serverless_mac_binary == serverless_hashes[index]
  loop: "{{ serverless_hashes }}"
  loop_control:
    index_var: index

- name: Match hash for Linux serverless (kn) binary
  ansible.builtin.set_fact:
    serverless_linux_hash: "{{ serverless_hashes[index - 1] }}"
  when: serverless_linux_binary == serverless_hashes[index | int]
  loop: "{{ serverless_hashes }}"
  loop_control:
    index_var: index

- name: Creating openshift-serverless.rb Forumla from template
  ansible.builtin.template:
    src: "templates/openshift-serverless.j2"
    dest: "{{ formula_directory }}/openshift-serverless.rb"
    mode: "0644"
