- name: Figuring out the latest odo version - step 1 - getting list
  ansible.builtin.uri:
    url: "{{ rosa_url }}?F=0"
    return_content: yes
  retries: 3
  delay: 3
  register: rosa_dir_list

- name: Getting version - step 2 - parsing html
  ansible.builtin.set_fact:
    rosa_temp_1: "{{ rosa_dir_list.content.split() }}"

- name: Getting version - step 3 - parsing html (again)
  ansible.builtin.set_fact:
    rosa_temp_2: "{{ item.split('/') }}"
  loop: "{{ rosa_temp_1 }}"
  when: item is regex("^[0-9]*\\.[0-9]*\\.[0-9]*")

- name: Getting version - step 4 - setting the version
  ansible.builtin.set_fact:
    rosa_version: "{{ rosa_temp_2.0 }}"

- name: Get sha256sum.txt for rosa
  ansible.builtin.uri:
    url: "{{ rosa_url }}/{{ rosa_version }}/{{ hash_file }}"
    return_content: yes
  retries: 3
  delay: 3
  register: rosa_hash_file

- name: Split up the downloaded sha256sum file
  ansible.builtin.set_fact:
    rosa_hashes: "{{ rosa_hash_file.content.split() }}"

- name: Match hash for Mac rosa binary
  ansible.builtin.set_fact:
    rosa_mac_hash: "{{ rosa_hashes[index - 1] }}"
  when: rosa_mac_binary == rosa_hashes[index]
  loop: "{{ rosa_hashes }}"
  loop_control:
    index_var: index

- name: Match hash for Linux rosa binary
  ansible.builtin.set_fact:
    rosa_linux_hash: "{{ rosa_hashes[index - 1] }}"
  when: rosa_linux_binary == rosa_hashes[index | int]
  loop: "{{ rosa_hashes }}"
  loop_control:
    index_var: index

- name: Creating rosa.rb Forumla from template
  ansible.builtin.template:
    src: "templates/rosa.j2"
    dest: "{{ formula_directory }}/rosa.rb"
    mode: "0644"
